# .chainlit/config.toml  — v2-compatible
enable_telemetry = false       # keep if you wish

[UI]
name        = "Pasante AI ver1.0"
description = "Powered by Inferencia Digital"
custom_css  = "/public/overrides.css"

